name: Bug report 2
description: Template for bug reports
title: '[Bug]: '
projects: ["caghetti/1"]
labels:
  - bug
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty
      options:
        - hard
        - medium
        - easy
    validations:
      required: true
  - type: checkboxes
    id: asked_by_customer
    attributes:
      label: Asked by customer
      description: Has  the customer discover the bug
      options:
        - label: 'yes'
          required: false
  - type: checkboxes
    id: regression
    attributes:
      label: Regression
      description: Is the bug a regression ?
      options:
        - label: 'yes'
          required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: describe the bug
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To reproduce
      description: 'Steps to reproduce the behavior:'
      placeholder: 1. Go to '...' 2. Click on '....' 3. Scroll down to '....' 4. See error
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Copy your screenshots here
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: >-
        Add any other context about the problem here : Solution, sources
        impacted
